services:
  db:
    image: postgres:13.2
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts:/scripts
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123123
    ports:
      - "5436:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d blog"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - datablog-net

  # alembic:
  #   image: fastapi-base:latest
  #   environment:
  #     SQL_DATABASE_URL: "postgresql+psycopg2://admin:123123@db:5432/blog"
  #     SECRET_KEY: ${SECRET_KEY}
  #     PYTHONPATH: /app
  #   working_dir: /app
  #   command: [ "alembic", "upgrade", "head" ]
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - datablog-net

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - datablog-net

  app:
    build: .
    image: hung286/blog_be:latest
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DATABASE_URL: "postgresql+psycopg2://admin:123123@db:5432/blog"
      SECRET_KEY: ${SECRET_KEY}
      MINIO_ENDPOINT: "http://minio:9000" # internal docker network endpoint
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: blog-images
      MINIO_PUBLIC_URL: "http://localhost:9000" # public URL for clients to access images
    ports:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - datablog-net
    volumes:
      - ./app:/app/app

volumes:
  minio_data:
  db_data:

networks:
  datablog-net:
    driver: bridge
